FROM node:20-alpine
WORKDIR /app
RUN apk add --no-cache openssl
COPY package*.json ./
COPY prisma ./prisma
RUN npm install
COPY . .
EXPOSE 5000
CMD ["sh", "-c", "npx prisma migrate deploy && node server.js"]
